---
# controller_credentials:
#   - name: Amazon Web Services
#     description: created by Ansible
#     organization: Default
#     credential_type: Amazon Web Services
#     inputs:
#       username: "{{ aws_access_key }}"
#       password: "{{ aws_secret_key }}"
  # - name: ServiceNow
  #   description: created by Ansible
  #   organization: Default
  #   credential_type: ServiceNow Credential
  #   inputs:
  #     SN_HOST: "{{ snow_host}}"
  #     SN_PASSWORD: "{{ snow_password }}"
  #     SN_USERNAME: "{{ snow_username }}"
  # - name: certified
  #   description: created by Ansible
  #   organization: Default
  #   credential_type: Ansible Galaxy/Automation Hub API Token
  #   inputs:
  #     url: "https://console.redhat.com/api/automation-hub/content/published/"
  #     auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
  #     token: "{{ hub_token }}"
  # - name: validated
  #   description: created by Ansible
  #   organization: Default
  #   credential_type: Ansible Galaxy/Automation Hub API Token
  #   inputs:
  #     url: "https://console.redhat.com/api/automation-hub/content/validated/"
  #     auth_url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
  #     token: "{{ hub_token }}"