---
# controller_credential_types:
  # - name: ServiceNow Credential
  #   description: ServiceNow Credential
  #   kind: cloud
  #   inputs:
  #     fields:
  #       - id: SN_HOST
  #         type: string
  #         label: Snow Instance
  #       - id: SN_USERNAME
  #         type: string
  #         label: Username
  #       - id: SN_PASSWORD
  #         type: string
  #         label: Password
  #         secret: true
  #     required:
  #       - SN_HOST
  #       - SN_USERNAME
  #       - SN_PASSWORD
  #   injectors:
  #     env:
  #       SN_HOST:  !unsafe "{{ SN_HOST }}"
  #       SN_PASSWORD:  !unsafe "{{ SN_PASSWORD }}"
  #       SN_USERNAME:  !unsafe "{{ SN_USERNAME }}"