---
# Commented out content is serving as example for you to add new content.
controller_inventories:
  # - name: Demo Inventory
  #   new_name: localhost
  #   description: inventory for localhost
  #   organization: Default
  - name: OpenShift Virtual Machines
    description: Load inventory from Openshift Virtualization
    organization: Default
  - name: Amazon Web Services
    description: Load inventory from AWS 
    organization: Default