---
controller_configuration_projects_async_retries: 60
controller_configuration_projects_async_delay: 5
controller_projects:
  - name: Demo Project
    state: absent
  - name: Ansible Configuration As Code
    scm_type: git
    scm_url: https://github.com/AlmendraSalgado/ansible_aap_as_code.git
    scm_branch: main
    scm_clean: true
    description: Ansible Configuration As Code
    organization: Default
    scm_update_on_launch: true
    verbosity: 0
    wait: true
    update_project: true
  - name: Ansible Openshift Virtualization
    scm_type: git
    scm_url: https://github.com/AlmendraSalgado/ansible_ocp_virt.git
    scm_branch: main
    scm_clean: true
    description: Ansible Openshift Virtualization
    organization: Default
    scm_update_on_launch: true
    wait: true
    update_project: true
    verbosity: 0
  - name: Ansible Linux
    scm_type: git
    scm_url: https://github.com/AlmendraSalgado/ansible_linux.git
    scm_branch: main
    scm_clean: true
    description: Ansible Linux
    organization: Default
    scm_update_on_launch: true
    wait: true
    update_project: true
    verbosity: 0
  - name: Ansible ServiceNow
    scm_type: git
    scm_url: https://github.com/AlmendraSalgado/ansible_snow.git
    scm_branch: main
    scm_clean: true
    description: Ansible ServiceNow
    organization: Default
    scm_update_on_launch: true
    wait: true
    update_project: true
    verbosity: 0
  - name: Ansible Cloud
    scm_type: git
    scm_url: https://github.com/AlmendraSalgado/ansible_cloud.git
    scm_branch: main
    scm_clean: true
    description: Ansible ServiceNow
    organization: Default
    scm_update_on_launch: true
    wait: true
    update_project: true
    verbosity: 0