---
controller_workflows:
  - name: New RHEL Server RITM from ServiceNow
    ask_variables_on_launch: true
    state: present

    workflow_nodes:

      - identifier: 101-manage-vm
        unified_job_template:
          name: AWS - Provision new VM
          type: job_template
          organization:
            name: Default
        related:
          success_nodes:
            - identifier: 201-sync-inventory

      - identifier: 201-sync-inventory
        unified_job_template:
          name: Amazon EC2 Source
          type: inventory_source
          inventory:
            organization:
              name: Default
        related:
          success_nodes:
            - identifier: 301-create-ci

      - identifier: 301-create-ci
        unified_job_template:
          name: SNOW - Create a Configuration Item (CI)
          type: job_template
          organization:
            name: Default     
            
  # - name: Update Openshift Virtual Machines
  #   state: present
  #   webhook_service: github
  #   webhook_credential: GitHub PAT

  #   workflow_nodes:

  #     - identifier: 101-sync-project
  #       unified_job_template:
  #         name: Ansible Openshift Virtualization
  #         type: project
  #         organization:
  #           name: Default
  #       related:
  #         success_nodes:
  #           - identifier: 201-manage-vm

  #     - identifier: 201-manage-vm
  #       unified_job_template:
  #         name: Manage VMs
  #         type: job_template
  #         organization:
  #           name: Default
  #       related:
  #         success_nodes:
  #           - identifier: 301-sync-inventory

  #     - identifier: 301-sync-inventory
  #       unified_job_template:
  #         name: OpenShift Virtual Machines Source
  #         type: inventory_source
  #         inventory:
  #           organization:
  #             name: Default
      
