---
eda_decision_environments:
  - name: Default Decision Environment
    description: minimal decision environment
    organization: Default
    image_url: registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel9:latest