---
eda_credentials:
  - name: Red Hat Ansible Automation Platform
    description: created by Ansible
    credential_type: Red Hat Ansible Automation Platform
    organization: Default
    inputs:
      username: "{{ aap_username }}"
      password: "{{ aap_password }}"
      host: "{{ aap_hostname }}/api/controller/"
  - name: ServiceNow
    description: created by Ansible
    credential_type: ServiceNow Event Stream
    organization: Default
    inputs:
      token: "{{ snow_bearer_token }}"
