---
# eda_rulebook_activations:
#   - name: RITM - ServiceNow
#     description: rulebook activation for events from ServiceNow
#     organization: Default
#     project: Ansible ServiceNow
#     rulebook: requested-items.yml
#     decision_environment: Default Decision Environment
#     enabled: true
#     state: present
#     eda_credentials:
#       - Red Hat Ansible Automation Platform
#     event_streams: 
#       - event_stream: ServiceNow
#         source_name: __SOURCE_1