---
controller_configuration_projects_async_retries: 60
controller_configuration_projects_async_delay: 5
controller_projects:
  - name: Ansible CaC
    scm_type: git
    scm_url: https://github.com/AlmendraSalgado/ansible_aap_as_code.git
    scm_branch: main
    scm_clean: true
    description: Ansible Configuration As Code
    organization: Default
    extra_vars:
      aap_configs_dir: "/runner/project/configs"
    scm_update_on_launch: true
    verbosity: 0
    wait: true
    update_project: true
  - name: Ansible Openshift Virtualization
    scm_type: git
    scm_url: https://github.com/AlmendraSalgado/ansible_ocp_virt.git
    scm_branch: main
    scm_clean: true
    description: Ansible Openshift Virtualization
    organization: Default
    scm_update_on_launch: true
    wait: true
    update_project: true
    verbosity: 0