---
controller_workflows:
  - name: Simple workflow schema
    state: present
    webhook_service: github
    webhook_credential: GitHub PAT

    workflow_nodes:

      - identifier: 101-sync-project
        unified_job_template:
          name: Ansible CaC
          type: project
          organization:
            name: Default
        related:
          success_nodes:
            - identifier: 201-manage-vm

      - identifier: 201-manage-vm
        unified_job_template:
          name: Manage VMs
          type: job_template
          organization:
            name: Default
        related:
          success_nodes:
            - identifier: 301-sync-inventory

      - identifier: 301-sync-inventory
        unified_job_template:
          name: OpenShift Virtual Machines Source
          type: inventory_source
          inventory:
            organization:
              name: Default